name: macos_unit_tests

on: [push]

jobs:
  macOS:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - uses: tlambert03/setup-qt-libs@v1

    - name: Install dependencies
      run: |
        brew install openscad
        ln -s /Applications/OpenSCAD.app/Contents/MacOS/OpenSCAD /usr/local/bin/openscad
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Test with pytest
      uses: GabrielBB/xvfb-action@v1
      with:
          run: python -m pytest
