name: python application

on:
  push:
    branches:
      - master

jobs:
  test:
    name: ${{ matrix.platform  }} py${{ matrix.python-version }}
    runs-on: ${{ matrix.platform }}
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-latest, windows-latest, macos-latest]
        python-version: [3.9]
        qt-lib: [pyqt5]
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - uses: tlambert03/setup-qt-libs@v1

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Test with pytest
      uses: GabrielBB/xvfb-action@v1
      with:
        run: python -m pytest
