name: windows_unit_tests

on: [push]

jobs:
  windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - uses: tlambert03/setup-qt-libs@v1

    - name: Install OpenSCAD
      run: choco install  openscad

    - name: Add OSC to path
      run:  |
        echo "C:\Program Files\OpenSCAD" >> $GITHUB_PATH
        echo $GITHUB_PATH
        dir "C:\Program Files"


    - name: install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Test with pytest
      uses: GabrielBB/xvfb-action@v1
      with:
          run: python -m pytest
